Added Two things that happened in the Rust China community this week
rust-lang/this-week-in-rust pull request #2555
Opened 2021-11-01 05:53 UTC by ZhangHanDong

- [[ZH] Rust Chinese Magazine Issue 10 has been released!](https://rustmagazine.github.io/rust_magazine_2021/chapter_10/toc.html)
- [[ZH] The first draft of the Rust Secure Coding Specification in Chinese has been released. Everyone is welcome to contribute](https://rust-coding-guidelines.github.io/rust-coding-guidelines-zh/)

2021-11-02 01:00 UTC, nellshamrell commented
@MATRIXKOO and @Folyd do you mind helping me review these two articles?

2021-11-02 01:09 UTC, PsiACE approved these changes
LGTM, cc @nellshamrell

2021-11-02 01:11 UTC, PsiACE requested changes

2021-11-02 01:11 UTC, PsiACE commented on draft/2021-11-03-this-week-in-rust.md
> +!](https://rustmagazine.github.io/rust_magazine_2021/chapter_10/toc.html)
pls fix format and display, cc @ZhangHanDong

2021-11-02 02:47 UTC, ZhangHanDong commented
A new article has been added, a total of three articles

2021-11-02 02:50 UTC, MATRIXKOO commented
Greate guidelines. 
And [\[ZH\] Trojan Source｜ Hiding invisible vulnerabilities in Rust code](https://zhuanlan.zhihu.com/p/428305373) is an interpretation for Chinese readers.

2021-11-02 02:54 UTC, MATRIXKOO reviewed
[\[ZH\] Trojan Source｜ Hiding invisible vulnerabilities in Rust code](https://zhuanlan.zhihu.com/p/428305373) viewed.

2021-11-02 03:01 UTC, Folyd approved these changes
LGTM.

2021-11-03 00:44 UTC, nellshamrell commented
Thank you so much, @MATRIXKOO and @Folyd!

2021-11-03 00:44 UTC, merged