Add Iran rust meetup event
rust-lang/this-week-in-rust pull request #3524
Opened 2022-08-08 13:08 UTC by hamidrezakp

2022-08-09 22:42 UTC, mariannegoldin commented
Thank you for the PR! The link included points to an older meetup. Is there another link you would prefer to use for the 8/18/22 event?

2022-08-10 08:10 UTC, hamidrezakp commented
> 
 oh, the link is correct, we had a problem with last meetup and it didn't started, so we are using that number :))

2022-08-10 08:22 UTC, hamidrezakp commented
I have updated the meetup website, so it's all correct now

2022-08-10 21:38 UTC, andrewpollack requested changes
Once this change is committed, this will be good to merge!

2022-08-10 21:38 UTC, andrewpollack commented on draft/2022-08-10-this-week-in-rust.md
> +    * [**Iran Rust Meetup #8**](https://rust-meetup.ir/2022/07/22/8th-meetup.html)
```suggestion
    * [**Iran Rust Meetup #8**](https://rust-meetup.ir/2022/08/18/8th-meetup.html)
```
URL change needed for date

2022-08-10 22:11 UTC, hamidrezakp commented
> Once this change is committed, this will be good to merge!

You are absolutely right, thanks for seeing my error :))

2022-08-10 22:37 UTC, andrewpollack commented
Looks great; thank you!!

2022-08-10 22:37 UTC, merged