Add `RustShip: a new Rust podcast`
rust-lang/this-week-in-rust pull request #4636
Opened 2023-08-18 16:04 UTC by MarcoIeni

2023-08-21 14:13 UTC, bennyvasquez requested changes
We ask folks to label non-text links with the type of media they are. Suggesting the change here, so you can see what I mean for future submissions!

2023-08-21 14:13 UTC, bennyvasquez commented on draft/2023-08-23-this-week-in-rust.md
> +* [RustShip: a new Rust podcast](https://ieni.dev/2023/08/rustship-a-new-rust-podcast/)
```suggestion
* [audio] [RustShip: a new Rust podcast](https://ieni.dev/2023/08/rustship-a-new-rust-podcast/)
```

2023-08-21 19:03 UTC, MarcoIeni commented
sure, thanks!

2023-08-22 17:10 UTC, bennyvasquez commented
Thank you!

2023-08-22 17:10 UTC, merged